[package]
name = "eth_event_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.18.0"
tokio = "1.19.2"
anyhow = "1.0"
hex = "0.4.3"
ethabi = "17.0.0"
nom = "7.1.1"
tokio-retry = "0.3"

[[example]]
name = "stream_live"
