[package]
name = "eth_event_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "1.0.98"
quote = "1.0"
eth_event_stream = { version = "0.1.0", path = "../eth_event_stream" }
ethabi = "16.0.0"
anyhow = "1.0"
ethereum-types = "0.12.1"

[lib]
proc-macro = true
